# Generated by Django 5.2.8 on 2026-09-25 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='deposit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bids', to='auction.deposit'),
        ),
    ]
