# Generated by Django 5.2.8 on 2026-09-25 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_restrict_bid_deposit_delete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='buy_now_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='BuyNowPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending payment'), ('paid', 'Paid (won)'), ('refunded', 'Refunded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('provider', models.CharField(max_length=50)),
                ('provider_reference', models.CharField(blank=True, max_length=255)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='auction.auction')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_now_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Buy-now purchase',
                'verbose_name_plural': 'Buy-now purchases',
            },
        ),
        migrations.AddField(
            model_name='auction',
            name='winning_purchase',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_auction', to='auction.buynowpurchase'),
        ),
        migrations.AddConstraint(
            model_name='buynowpurchase',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'paid')), fields=('auction',), name='one_paid_buy_now_per_auction'),
        ),
        migrations.AddConstraint(
            model_name='buynowpurchase',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('auction', 'buyer'), name='one_pending_buy_now_per_buyer'),
        ),
    ]
