# Generated by Django 5.2.8 on 2026-09-25 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_buy_now_purchases'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('unpaid_buy_now', 'Started buy-now, never paid'), ('winner_defaulted', "Won, didn't pay"), ('seller_no_show', "Seller didn't hand over"), ('dispute_lost', 'Seller lost a dispute')], max_length=30)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to=settings.AUTH_USER_MODEL)),
                ('auction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='auction.auction')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('bid', 'Winning bid'), ('buy_now', 'Buy now'), ('runner_up', 'Runner-up offer')], max_length=20)),
                ('status', models.CharField(choices=[('offered', 'Offered to runner-up'), ('awaiting_payment', 'Awaiting payment'), ('paid', 'Paid (awaiting handover)'), ('handed_over', 'Handed over'), ('completed', 'Completed'), ('disputed', 'Problem reported'), ('buyer_defaulted', "Buyer didn't pay"), ('declined', 'Offer declined or expired'), ('seller_defaulted', "Seller didn't hand over"), ('refunded', 'Refunded after review')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance_status', models.CharField(choices=[('none', 'Nothing owed'), ('pending', 'Pending payment'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='none', max_length=20)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('provider_reference', models.CharField(blank=True, max_length=255)),
                ('payment_due_at', models.DateTimeField(blank=True, null=True)),
                ('handover_due_at', models.DateTimeField(blank=True, null=True)),
                ('confirm_due_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('handed_over_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_out_at', models.DateTimeField(blank=True, help_text='When staff paid the seller', null=True)),
                ('handover_note', models.CharField(blank=True, help_text="Seller's note, e.g. courier and tracking number", max_length=300)),
                ('problem_report', models.TextField(blank=True)),
                ('runner_up_decision', models.CharField(blank=True, choices=[('offered', 'Offered'), ('declined', 'Not offered')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='auction.auction')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('deposit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='auction.deposit')),
                ('purchase', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='auction.buynowpurchase')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SellerBond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending payment'), ('held', 'Held'), ('forfeited', 'Forfeited'), ('released', 'Released'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('provider', models.CharField(max_length=50)),
                ('provider_reference', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_bond', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seller bond',
                'verbose_name_plural': 'Seller bonds',
            },
        ),
    ]
