# Generated by Django 5.2.8 on 2026-09-25 04:44

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_account_contact_details'),
        ('auction', '0004_orders_bonds_incidents'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountToReview',
            fields=[
            ],
            options={
                'verbose_name': 'Account to review',
                'verbose_name_plural': 'Accounts to review',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.account',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
