# Generated by Django 5.2.8 on 2026-09-28 16:11

import auction.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction", "0005_account_to_review"),
        ("post", "0019_contact_request_replied_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="equipment_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=auction.models.cascade_unless_money_held,
                related_name="auctions",
                to="post.equipmentpost",
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="live_animal_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=auction.models.cascade_unless_money_held,
                related_name="auctions",
                to="post.liveanimalpost",
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="seller",
            field=models.ForeignKey(
                on_delete=auction.models.cascade_unless_money_held,
                related_name="auctions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="buynowpurchase",
            name="auction",
            field=models.ForeignKey(
                on_delete=auction.models.cascade_unless_money_held,
                related_name="purchases",
                to="auction.auction",
            ),
        ),
        migrations.AlterField(
            model_name="buynowpurchase",
            name="buyer",
            field=models.ForeignKey(
                on_delete=auction.models.cascade_unless_money_held,
                related_name="buy_now_purchases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="deposit",
            name="account",
            field=models.ForeignKey(
                on_delete=auction.models.cascade_unless_money_held,
                related_name="auction_deposits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="deposit",
            name="auction",
            field=models.ForeignKey(
                on_delete=auction.models.cascade_unless_money_held,
                related_name="deposits",
                to="auction.auction",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="auction",
            field=models.ForeignKey(
                on_delete=auction.models.cascade_unless_money_held,
                related_name="orders",
                to="auction.auction",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="buyer",
            field=models.ForeignKey(
                on_delete=auction.models.cascade_unless_money_held,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="sellerbond",
            name="account",
            field=models.OneToOneField(
                on_delete=auction.models.cascade_unless_money_held,
                related_name="seller_bond",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
