# Generated by Django 5.2.8 on 2026-09-28 17:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction", "0006_protect_auction_money_on_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="fee_rate",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0"), max_digits=5
            ),
        ),
    ]
