# Generated by Django 5.2.8 on 2026-02-14 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contact_info', models.CharField(choices=[('TPE', '臺北市'), ('NWT', '新北市'), ('TYN', '桃園市'), ('TXG', '臺中市'), ('TNN', '臺南市 '), ('KHH', '高雄市'), ('KEE', '基隆市'), ('HSZ', '新竹市'), ('CYI', '嘉義市'), ('HSQ', '新竹縣'), ('MIA', '苗栗縣'), ('CHA', '彰化縣'), ('NAN', '南投縣'), ('YUN', '雲林縣'), ('CYQ', '嘉義縣'), ('PIF', '屏東縣'), ('ILA', '宜蘭縣'), ('HUA', '花蓮縣'), ('TTT', '臺東縣'), ('PEN', '澎湖縣'), ('KIN', '金門縣'), ('LIE', '連江縣'), ('OTH', '其他')], default='OTH', max_length=5)),
                ('location', models.CharField(max_length=200)),
                ('media_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condition', models.IntegerField(choices=[(2, 'New'), (1, 'Used'), (0, 'Not Functional')], default=1)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LiveAnimalPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contact_info', models.CharField(choices=[('TPE', '臺北市'), ('NWT', '新北市'), ('TYN', '桃園市'), ('TXG', '臺中市'), ('TNN', '臺南市 '), ('KHH', '高雄市'), ('KEE', '基隆市'), ('HSZ', '新竹市'), ('CYI', '嘉義市'), ('HSQ', '新竹縣'), ('MIA', '苗栗縣'), ('CHA', '彰化縣'), ('NAN', '南投縣'), ('YUN', '雲林縣'), ('CYQ', '嘉義縣'), ('PIF', '屏東縣'), ('ILA', '宜蘭縣'), ('HUA', '花蓮縣'), ('TTT', '臺東縣'), ('PEN', '澎湖縣'), ('KIN', '金門縣'), ('LIE', '連江縣'), ('OTH', '其他')], default='OTH', max_length=5)),
                ('location', models.CharField(max_length=200)),
                ('media_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('involved_species', models.ManyToManyField(to='post.species')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
