# Generated by Django 5.2.8 on 2026-02-14 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentpost',
            name='contact_info',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='equipmentpost',
            name='location',
            field=models.CharField(choices=[('TPE', '臺北市'), ('NWT', '新北市'), ('TYN', '桃園市'), ('TXG', '臺中市'), ('TNN', '臺南市 '), ('KHH', '高雄市'), ('KEE', '基隆市'), ('HSZ', '新竹市'), ('CYI', '嘉義市'), ('HSQ', '新竹縣'), ('MIA', '苗栗縣'), ('CHA', '彰化縣'), ('NAN', '南投縣'), ('YUN', '雲林縣'), ('CYQ', '嘉義縣'), ('PIF', '屏東縣'), ('ILA', '宜蘭縣'), ('HUA', '花蓮縣'), ('TTT', '臺東縣'), ('PEN', '澎湖縣'), ('KIN', '金門縣'), ('LIE', '連江縣'), ('OTH', '其他')], default='OTH', max_length=5),
        ),
        migrations.AlterField(
            model_name='liveanimalpost',
            name='contact_info',
            field=models.CharField(max_length=200),
        ),
        migrations.RemoveField(
            model_name='liveanimalpost',
            name='involved_species',
        ),
        migrations.AlterField(
            model_name='liveanimalpost',
            name='location',
            field=models.CharField(choices=[('TPE', '臺北市'), ('NWT', '新北市'), ('TYN', '桃園市'), ('TXG', '臺中市'), ('TNN', '臺南市 '), ('KHH', '高雄市'), ('KEE', '基隆市'), ('HSZ', '新竹市'), ('CYI', '嘉義市'), ('HSQ', '新竹縣'), ('MIA', '苗栗縣'), ('CHA', '彰化縣'), ('NAN', '南投縣'), ('YUN', '雲林縣'), ('CYQ', '嘉義縣'), ('PIF', '屏東縣'), ('ILA', '宜蘭縣'), ('HUA', '花蓮縣'), ('TTT', '臺東縣'), ('PEN', '澎湖縣'), ('KIN', '金門縣'), ('LIE', '連江縣'), ('OTH', '其他')], default='OTH', max_length=5),
        ),
        migrations.AddField(
            model_name='liveanimalpost',
            name='involved_species',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='post.species'),
        ),
    ]
