# Generated by Django 5.2.8 on 2026-02-14 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_equipmentpost_contact_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liveanimalpost',
            old_name='involved_species',
            new_name='specie',
        ),
    ]
