# Generated by Django 5.2.8 on 2026-02-14 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_involved_species_liveanimalpost_specie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liveanimalpost',
            old_name='specie',
            new_name='species',
        ),
    ]
