# Generated by Django 5.2.8 on 2026-09-01 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_rename_specie_liveanimalpost_species'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentpost',
            options={'verbose_name': 'Equipment Post', 'verbose_name_plural': 'Equipment Posts'},
        ),
        migrations.AlterModelOptions(
            name='liveanimalpost',
            options={'verbose_name': 'Live Animal Post', 'verbose_name_plural': 'Live Animal Posts'},
        ),
        migrations.RemoveField(
            model_name='equipmentpost',
            name='media_url',
        ),
        migrations.RemoveField(
            model_name='liveanimalpost',
            name='media_url',
        ),
        migrations.AddField(
            model_name='equipmentpost',
            name='shipping_methods',
            field=models.JSONField(default=list, help_text="List of shipping methods: ['localPickup', 'shipping']"),
        ),
        migrations.AddField(
            model_name='equipmentpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='liveanimalpost',
            name='age_years',
            field=models.FloatField(blank=True, help_text='Age in years', null=True),
        ),
        migrations.AddField(
            model_name='liveanimalpost',
            name='diets',
            field=models.JSONField(default=list, help_text="List of diets: ['live', 'frozenThawed', 'pellets']"),
        ),
        migrations.AddField(
            model_name='liveanimalpost',
            name='genetics',
            field=models.TextField(blank=True, help_text="Genetic traits separated by '/', e.g. 'Pastel/Pied'"),
        ),
        migrations.AddField(
            model_name='liveanimalpost',
            name='life_stage',
            field=models.CharField(choices=[('hatchling', 'Hatchling'), ('juvenile', 'Juvenile'), ('subAdult', 'Sub-Adult'), ('adult', 'Adult')], default='adult', max_length=20),
        ),
        migrations.AddField(
            model_name='liveanimalpost',
            name='sex',
            field=models.CharField(choices=[('1.0', 'Male (1.0)'), ('0.1', 'Female (0.1)'), ('unsexed', 'Unsexed')], default='unsexed', max_length=20),
        ),
        migrations.AddField(
            model_name='liveanimalpost',
            name='shipping_methods',
            field=models.JSONField(default=list, help_text="List of shipping methods: ['localPickup', 'shipping']"),
        ),
        migrations.AddField(
            model_name='liveanimalpost',
            name='size_cm',
            field=models.FloatField(blank=True, help_text='Size/Length in centimeters', null=True),
        ),
        migrations.AddField(
            model_name='liveanimalpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='liveanimalpost',
            name='weight_grams',
            field=models.FloatField(blank=True, help_text='Weight in grams', null=True),
        ),
        migrations.AlterField(
            model_name='equipmentpost',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipmentpost',
            name='condition',
            field=models.IntegerField(choices=[(0, 'Not Functional'), (1, 'Used'), (2, 'New')], default=1),
        ),
        migrations.AlterField(
            model_name='liveanimalpost',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='liveanimalpost',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_posts', to='post.species'),
        ),
    ]
