# Generated by Django 5.2.8 on 2026-09-03 18:17

from django.db import migrations, models
from django.utils import timezone
from datetime import timedelta
import json


def seed_demo_listings(apps, schema_editor):
    Account = apps.get_model('account', 'Account')
    Species = apps.get_model('post', 'Species')
    LiveAnimalPost = apps.get_model('post', 'LiveAnimalPost')

    listings = [
        ('Apex Exotics', 'Ball Pythons', 'Super Pastel Pied', '1.0', 450, 'TPE', 'Pastel/Pied', 'adult', 4, 1800, 120, ['frozenThawed'], ['shipping', 'localPickup'], 12, '1531386151447-fd76ad50012f', 'Healthy, well-fed male ball python with excellent pattern and calm handling.', 'Available for local pickup or secure shipping.', '+886 912 345 678', 'apex.exotics@example.com', '@apex.exotics'),
        ('High Ridge Geckos', 'Crested Geckos', 'Lilly White Crested Gecko', '0.1', 850, 'NWT', 'Lilly White', 'juvenile', 1.5, 35, 18, ['live', 'frozenThawed'], ['shipping'], 4, '1504450758481-7338eba7524a', 'Beautiful lilly white gecko with soft color contrast and alert personality.', 'Strong feeder response and robust health.', '+886 966 334 702', 'highridge.geckos@example.com', '@highridgegeckos'),
        ('Morph Kingdom', 'Ball Pythons', 'Enchi Clown', '0.1', 650, 'TXG', 'Enchi/Clown', 'adult', 3, 1600, 125, ['frozenThawed'], ['localPickup'], 30, '1548767797-d8c844163c4c', 'A calm and well-established adult female with distinct clown and enchi markings.', 'Located near Taichung. Local pickup available.', '+886 912 440 810', 'morphkingdom@example.com', '@morphkingdom'),
        ('Desert Scales', 'Leopard Geckos', 'Tangerine Tremper Albino', '1.0', 220, 'TPE', 'Tremper Albino/Tangerine', 'adult', 2, 70, 22, ['live'], ['shipping', 'localPickup'], 90, '1563409236302-8442b5e644df', 'Vibrant tiger-striped leopard gecko with strong orange tones.', 'Perfect for a hobby breeder or dedicated pet owner.', '+886 980 093 499', 'desertscales@example.com', '@desertscales'),
        ('Emerald Scale Co.', 'Ball Pythons', 'Pastel Banana Ball Python', '1.0', 780, 'NWT', 'Pastel/Banana', 'juvenile', 1, 650, 110, ['frozenThawed'], ['shipping'], 8, '1516728778615-2d590ea1856f', 'Young male with a warm pastel banana appearance and curious temperament.', 'Suitable for a keeper starting a striking collection.', '+886 915 752 100', 'emeraldscale@example.com', '@emeraldscaleco'),
        ('Moonlight Morphs', 'Leopard Geckos', 'Mack Snow Leopard Gecko', '0.1', 340, 'TYN', 'Mack Snow', 'subAdult', 1.8, 55, 20, ['live'], ['localPickup', 'shipping'], 16, '1526346698789-22fd84314424', 'An attractive subadult female with snow-banded patterning and a healthy routine.', 'Can be arranged with secure shipping or local pickup.', '+886 955 680 114', 'moonlightmorphs@example.com', '@moonlightmorphs'),
    ]

    for username, species_name, title, sex, price, location, genetics, life_stage, age, weight, size, diets, shipping, posted_days, image_id, description, guide_notes, phone, email, instagram in listings:
        account, _ = Account.objects.get_or_create(username=username, defaults={
            'email': email, 'seller_rating': 4.9, 'is_active': True,
        })
        species, _ = Species.objects.get_or_create(name=species_name)
        image = f'https://images.unsplash.com/photo-{image_id}?auto=format&fit=crop&w=1200&q=80'
        post, _ = LiveAnimalPost.objects.get_or_create(title=title, account=account, defaults={
            'description': description, 'price': price, 'location': location,
            'contact_info': json.dumps({'phone': phone, 'email': email, 'instagram': instagram}),
            'shipping_methods': shipping, 'species': species, 'sex': sex,
            'genetics': genetics, 'life_stage': life_stage, 'age_years': age,
            'weight_grams': weight, 'size_cm': size, 'diets': diets, 'image': image,
            'gallery': [image], 'guide_notes': guide_notes,
        })
        if post.created_at:
            LiveAnimalPost.objects.filter(pk=post.pk).update(
                created_at=timezone.now() - timedelta(days=posted_days)
            )


def remove_demo_listings(apps, schema_editor):
    LiveAnimalPost = apps.get_model('post', 'LiveAnimalPost')
    LiveAnimalPost.objects.filter(account__username__in=[
        'Apex Exotics', 'High Ridge Geckos', 'Morph Kingdom', 'Desert Scales',
        'Emerald Scale Co.', 'Moonlight Morphs',
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_equipmentpost_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveanimalpost',
            name='gallery',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='liveanimalpost',
            name='guide_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='liveanimalpost',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.RunPython(seed_demo_listings, remove_demo_listings),
    ]
