# Generated by Django 5.2.8 on 2026-09-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentpost',
            name='gallery',
            field=models.JSONField(default=list, help_text='All photo URLs, cover first'),
        ),
        migrations.AddField(
            model_name='equipmentpost',
            name='image',
            field=models.URLField(blank=True, help_text='Cover photo URL'),
        ),
        migrations.AlterField(
            model_name='liveanimalpost',
            name='gallery',
            field=models.JSONField(default=list, help_text='All photo URLs, cover first'),
        ),
        migrations.AlterField(
            model_name='liveanimalpost',
            name='image',
            field=models.URLField(blank=True, help_text='Cover photo URL'),
        ),
    ]
