# Generated by Django 5.2.8 on 2026-09-25 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_listing_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='buy_now',
            field=models.BooleanField(default=False),
        ),
    ]
