# Generated by Django 5.2.8 on 2026-09-25 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_contactrequest_buy_now'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactrequest',
            name='buy_now',
        ),
    ]
