# Generated by Django 5.2.8 on 2026-09-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0011_remove_contactrequest_buy_now"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipmentpost",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("reserved", "Reserved"),
                    ("sold", "Sold"),
                ],
                default="available",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="liveanimalpost",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("reserved", "Reserved"),
                    ("sold", "Sold"),
                ],
                default="available",
                max_length=20,
            ),
        ),
    ]
