# Generated by Django 5.2.8 on 2026-09-25 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0011_remove_contactrequest_buy_now"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="equipmentpost",
            name="is_hidden",
            field=models.BooleanField(
                default=False, help_text="Hidden from everyone but the owner and staff"
            ),
        ),
        migrations.AddField(
            model_name="liveanimalpost",
            name="is_hidden",
            field=models.BooleanField(
                default=False, help_text="Hidden from everyone but the owner and staff"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports_reviewed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="staff_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="report",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending review"),
                    ("resolved", "Resolved (action taken)"),
                    ("dismissed", "Dismissed (nothing wrong)"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
