# Generated by Django 5.2.8 on 2026-09-25 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0011_remove_contactrequest_buy_now"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipment_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="post.equipmentpost",
                    ),
                ),
                (
                    "live_animal_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="post.liveanimalpost",
                    ),
                ),
            ],
            options={
                "verbose_name": "Favorite",
                "verbose_name_plural": "Favorites",
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("equipment_post__isnull", True),
                                ("live_animal_post__isnull", False),
                            ),
                            models.Q(
                                ("equipment_post__isnull", False),
                                ("live_animal_post__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="favorite_has_exactly_one_listing",
                    ),
                    models.UniqueConstraint(
                        fields=("account", "live_animal_post"),
                        name="one_favorite_per_live_animal_post",
                    ),
                    models.UniqueConstraint(
                        fields=("account", "equipment_post"),
                        name="one_favorite_per_equipment_post",
                    ),
                ],
            },
        ),
    ]
