# Generated by Django 5.2.8 on 2026-09-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0011_remove_contactrequest_buy_now"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipmentpost",
            name="category",
            field=models.CharField(
                choices=[
                    ("enclosure", "Enclosure"),
                    ("heating", "Heating"),
                    ("lighting", "Lighting / UVB"),
                    ("climate", "Thermostats & monitoring"),
                    ("substrateDecor", "Substrate & decor"),
                    ("transport", "Carriers & transport"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
