# Generated by Django 5.2.8 on 2026-09-26 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0012_equipmentpost_category"),
        ("post", "0012_saved_search"),
    ]

    operations = []
