# Generated by Django 5.2.8 on 2026-09-26 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0013_merge_0012_equipmentpost_category_0012_favorite"),
        ("post", "0013_merge_0012_equipmentpost_category_0012_report_moderation"),
    ]

    operations = []
