# Generated by Django 5.2.8 on 2026-09-26 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0014_merge_listing_status_report_moderation"),
        ("post", "0014_merge_report_moderation_saved_search"),
    ]

    operations = []
