# Generated by Django 5.2.8 on 2026-09-26 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0015_merge_favorites_listing_status"),
        ("post", "0015_merge_listing_status_saved_search"),
    ]

    operations = []
