# Generated by Django 5.2.8 on 2026-09-26 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_merge_favorites_saved_search'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='liveanimalpost',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_posts', to='post.species'),
        ),
        migrations.CreateModel(
            name='SpeciesAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='post.species')),
            ],
            options={
                'verbose_name': 'Species alias',
                'verbose_name_plural': 'Species aliases',
            },
        ),
        migrations.CreateModel(
            name='SpeciesRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='As the seller typed it', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('staff_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='species_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('species', models.ForeignKey(blank=True, help_text='The species it was approved as', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='post.species')),
            ],
            options={
                'verbose_name': 'Species request',
                'verbose_name_plural': 'Species requests',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='liveanimalpost',
            name='species_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='post.speciesrequest'),
        ),
        migrations.AddConstraint(
            model_name='liveanimalpost',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('species__isnull', False), ('species_request__isnull', True)), models.Q(('species__isnull', True), ('species_request__isnull', False)), _connector='OR'), name='live_animal_post_has_species_or_request'),
        ),
    ]
