# Generated by Django 5.2.8 on 2026-09-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0018_seed_species_catalog"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactrequest",
            name="replied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
