# Generated by Django 5.2.8 on 2026-10-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0020_remove_sample_sellers"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipmentpost",
            name="thumbnail",
            field=models.URLField(
                blank=True,
                help_text="Card-sized copy of the cover photo",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="liveanimalpost",
            name="thumbnail",
            field=models.URLField(
                blank=True,
                help_text="Card-sized copy of the cover photo",
                max_length=300,
            ),
        ),
    ]
