"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

import dj_database_url
from datetime import date, timedelta
from decimal import Decimal

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_env_file(path):
    """Reads KEY=value lines from a local .env file; real environment variables take precedence."""
    if not path.exists():
        return
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        os.environ.setdefault(key.strip(), value.strip().strip('"\''))


def env_list(name, default=''):
    return [item.strip() for item in os.environ.get(name, default).split(',') if item.strip()]


def env_bool(name, default):
    value = os.environ.get(name)
    return default if value is None else value.lower() in ('1', 'true', 'yes')


def env_int(name, default):
    return int(os.environ.get(name, default))


def env_decimal(name, default):
    return Decimal(os.environ.get(name, default))


def env_date(name):
    value = os.environ.get(name)
    return date.fromisoformat(value) if value else None


load_env_file(BASE_DIR / '.env')

# `manage.py test` talks plain HTTP through the test client and must not share throttle counts.
TESTING = sys.argv[1:2] == ['test']


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# All deployment-specific values come from environment variables (or backend/.env locally; see
# .env.example). Defaults are production-safe: DEBUG is off unless explicitly enabled.
DEBUG = os.environ.get('DJANGO_DEBUG', '').lower() in ('1', 'true', 'yes')

SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured('Set DJANGO_SECRET_KEY (or DJANGO_DEBUG=1 for local development).')
    SECRET_KEY = 'django-insecure-local-development-only'

ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1' if DEBUG else '')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'django_filters',
    'post',
    'account',
    'authentication',
    'auction',
    'features',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # Serves the admin's CSS/JS from STATIC_ROOT in production, where nothing else serves /static/.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # Picks the response language from the frontend's Accept-Language header (see LANGUAGES below).
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'common.middleware.DevAuthBypassMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

AUTH_USER_MODEL = 'account.Account'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Production uses PostgreSQL from DATABASE_URL (Heroku Postgres sets it); without it, SQLite.
if os.environ.get('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.parse(
            os.environ['DATABASE_URL'],
            conn_max_age=600,
            conn_health_checks=True,
            # Heroku Postgres requires TLS; DJANGO_DATABASE_SSL=0 allows a local server without it.
            ssl_require=env_bool('DJANGO_DATABASE_SSL', not DEBUG),
        ),
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            # DJANGO_SQLITE_PATH lets the end-to-end tests run on a throwaway database.
            'NAME': Path(os.environ.get('DJANGO_SQLITE_PATH', BASE_DIR / 'db.sqlite3')),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# The whole policy: 8+ characters with both letters and numbers. The sign-up and reset forms list the
# same rules (Frontend/src/constants/passwordRules.js); keep them in step.
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},
    },
    {
        'NAME': 'common.passwords.LettersAndNumbersValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Singapore'

USE_I18N = True

# API messages (validation errors, action results) are translated; the frontend sends the user's
# UI language as Accept-Language. Our own strings live in locale/; Django/DRF ship their own.
LANGUAGES = [
    ('en', 'English'),
    ('zh-hant', '繁體中文'),
]
LOCALE_PATHS = [BASE_DIR / 'locale']

# Compiles locale/*.po before the tests; the .mo files aren't committed.
TEST_RUNNER = 'common.test_runner.CompilingTestRunner'

USE_TZ = True

# Email
# Prints "sent" emails to the console in dev; swap for a real backend in production.
EMAIL_BACKEND = os.environ.get('DJANGO_EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
# SMTP server for the smtp backend (any provider's SMTP relay, e.g. Resend or Amazon SES).
EMAIL_HOST = os.environ.get('DJANGO_EMAIL_HOST', 'localhost')
EMAIL_PORT = env_int('DJANGO_EMAIL_PORT', 587)
EMAIL_HOST_USER = os.environ.get('DJANGO_EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('DJANGO_EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = env_bool('DJANGO_EMAIL_USE_TLS', True)
EMAIL_TIMEOUT = 10  # a stuck mail server shouldn't hold a web request forever
DEFAULT_FROM_EMAIL = os.environ.get('DJANGO_DEFAULT_FROM_EMAIL', 'no-reply@reptile-marketplace.local')
# Staff addresses that get alerts (e.g. a buyer reporting a problem with an order), comma-separated.
ADMINS = [('Staff', address) for address in env_list('DJANGO_ADMINS')]

# Auctions (see auction/)
AUCTION_CURRENCY = 'TWD'
# Deposit a bidder pays before bidding: this share of the starting price, but never below the minimum.
AUCTION_DEPOSIT_RATE = Decimal('0.10')
AUCTION_MIN_DEPOSIT = Decimal('100.00')
AUCTION_MIN_DURATION_HOURS = 1
# Kept well under the 21 days a card processor lets a held deposit wait before it must be charged or
# released (ECPay), so every bidder's deposit can be a card hold.
AUCTION_MAX_DURATION_DAYS = env_int('AUCTION_MAX_DURATION_DAYS', 14)
# Anti-sniping: a bid in the last AUCTION_EXTEND_WINDOW_MINUTES pushes the end time to at least
# AUCTION_EXTEND_BY_MINUTES from that bid, so others get a chance to answer it. 0 turns it off.
AUCTION_EXTEND_WINDOW_MINUTES = env_int('AUCTION_EXTEND_WINDOW_MINUTES', 5)
AUCTION_EXTEND_BY_MINUTES = env_int('AUCTION_EXTEND_BY_MINUTES', 5)
# Where deposits, buy-now and order payments and seller bonds go; see auction/payments.py. Set
# AUCTION_PAYMENT_GATEWAY=auction.ecpay.ECPayGateway to take card payments through ECPay. Otherwise, in
# DEBUG payments count as paid instantly so the flows can be tried locally, and in production staff
# confirm them in the admin.
AUCTION_PAYMENT_GATEWAY = os.environ.get('AUCTION_PAYMENT_GATEWAY') or (
    'auction.payments.InstantPaymentGateway' if DEBUG else 'auction.payments.ManualPaymentGateway'
)
if AUCTION_PAYMENT_GATEWAY == 'auction.payments.InstantPaymentGateway' and not DEBUG:
    raise ImproperlyConfigured('InstantPaymentGateway treats every payment as paid; it is for local development only.')
# ECPay (auction/ecpay.py). The merchant ID, HashKey and HashIV come from ECPay's merchant back office.
# Payments go to ECPay's test site until ECPAY_LIVE is set, so a missing setting never takes real money.
ECPAY_MERCHANT_ID = os.environ.get('ECPAY_MERCHANT_ID', '')
ECPAY_HASH_KEY = os.environ.get('ECPAY_HASH_KEY', '')
ECPAY_HASH_IV = os.environ.get('ECPAY_HASH_IV', '')
ECPAY_LIVE = env_bool('ECPAY_LIVE', False)
# Turn on only after switching off automatic settlement (自動關帳) in ECPay's back office: deposits are
# then held on the bidder's card and released for free, and every other payment is settled as it arrives.
ECPAY_MANUAL_SETTLEMENT = env_bool('ECPAY_MANUAL_SETTLEMENT', False)

# After a sale (auction/models.py Order). Placeholder values: all of these are business decisions, so
# each can be changed with an environment variable without touching code.
# Hours the auction winner has to pay us the rest of the price; missing it forfeits their deposit.
ORDER_PAYMENT_HOURS = env_int('ORDER_PAYMENT_HOURS', 48)
# Hours a runner-up has to accept (pay for) an animal the seller offers them after the winner defaulted.
ORDER_RUNNER_UP_OFFER_HOURS = env_int('ORDER_RUNNER_UP_OFFER_HOURS', 48)
# Days the seller has, once we hold the full payment, to hand the animal over or ship it.
ORDER_HANDOVER_DAYS = env_int('ORDER_HANDOVER_DAYS', 5)
# Days the buyer then has to confirm it arrived intact (or report a problem) before the sale completes.
ORDER_CONFIRM_DAYS = env_int('ORDER_CONFIRM_DAYS', 3)
# Marketplace fee taken from the seller's payout on an auction sale, as a share of the price, by plan
# (Commercial or Commercial Pro). No cap: card processing costs grow with the price too. Each auction
# keeps the rate it started with (Auction.fee_rate), so a change only affects new auctions.
AUCTION_FEE_RATE_COMMERCIAL = env_decimal('AUCTION_FEE_RATE_COMMERCIAL', '0.05')
AUCTION_FEE_RATE_PRO = env_decimal('AUCTION_FEE_RATE_PRO', '0.03')
# Launch offer: no auction fee for a seller's first LAUNCH_OFFER_DAYS after joining, for accounts that
# joined before LAUNCH_OFFER_JOINED_BEFORE (YYYY-MM-DD). Unset means the offer is still open to
# everyone who joins; LAUNCH_OFFER_DAYS=0 ends it.
LAUNCH_OFFER_DAYS = env_int('LAUNCH_OFFER_DAYS', 182)
LAUNCH_OFFER_JOINED_BEFORE = env_date('LAUNCH_OFFER_JOINED_BEFORE')
# Monthly price of each paid plan in AUCTION_CURRENCY (returned by /api/v1/account/plans/). While
# there's no checkout, staff grant plans free by email and the upgrade page says "Free for now".
PLAN_PRICE_COMMERCIAL = env_decimal('PLAN_PRICE_COMMERCIAL', '299')
PLAN_PRICE_PRO = env_decimal('PLAN_PRICE_PRO', '499')
# What each plan allows (read through Account.max_post_count and max_images_per_post): listings an
# account may have, and photos per listing. Lowering a limit doesn't remove anything already posted; it
# only stops new listings or photos beyond it.
PLAN_HOBBYIST_MAX_LISTINGS = env_int('PLAN_HOBBYIST_MAX_LISTINGS', 5)
PLAN_HOBBYIST_MAX_PHOTOS = env_int('PLAN_HOBBYIST_MAX_PHOTOS', 3)
PLAN_COMMERCIAL_MAX_LISTINGS = env_int('PLAN_COMMERCIAL_MAX_LISTINGS', 20)
PLAN_COMMERCIAL_MAX_PHOTOS = env_int('PLAN_COMMERCIAL_MAX_PHOTOS', 6)
PLAN_PRO_MAX_LISTINGS = env_int('PLAN_PRO_MAX_LISTINGS', 200)
PLAN_PRO_MAX_PHOTOS = env_int('PLAN_PRO_MAX_PHOTOS', 12)
# Bond a seller leaves with us before starting auctions, forfeited if they take a buyer's money and
# never hand over. 0 turns the requirement off.
SELLER_BOND_AMOUNT = env_decimal('SELLER_BOND_AMOUNT', '0')
# Accounts with at least this many incidents (unpaid buy-nows, defaults, no-shows) are highlighted
# in the admin's "Accounts to review". Nothing is blocked automatically.
INCIDENT_REVIEW_THRESHOLD = env_int('INCIDENT_REVIEW_THRESHOLD', 2)
# A listing reported by this many different accounts (with the reports still pending) is hidden until
# staff review it, and staff are emailed. 0 turns auto-hiding off: reports then only queue for review.
REPORT_AUTO_HIDE_THRESHOLD = env_int('REPORT_AUTO_HIDE_THRESHOLD', 0)
# Saved searches a user may keep (each is emailed about by `manage.py send_search_alerts`).
SAVED_SEARCH_LIMIT = env_int('SAVED_SEARCH_LIMIT', 20)
# Where the website lives, for links in emails (e.g. https://example.com). No trailing slash.
FRONTEND_URL = os.environ.get('DJANGO_FRONTEND_URL', 'http://localhost:5173').rstrip('/')
# This API's own public address (e.g. https://api.example.com), for payment providers to call back.
BACKEND_URL = os.environ.get('DJANGO_BACKEND_URL', 'http://localhost:8000').rstrip('/')
# People who saved a listing get at most one price-drop email per listing in this many hours, so a
# seller can't mass-email them by lowering the price a little at a time.
PRICE_DROP_EMAIL_HOURS = env_int('PRICE_DROP_EMAIL_HOURS', 24)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# User-uploaded listing photos. Locally they're files in MEDIA_ROOT, served by Django when DEBUG is
# on. With DJANGO_S3_BUCKET set they go to S3 instead, since Heroku's disk is wiped on every restart.
MEDIA_URL = '/media/'
MEDIA_ROOT = Path(os.environ.get('DJANGO_MEDIA_ROOT', BASE_DIR / 'media'))

STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    # Compressed but not hashed names: hashing needs collectstatic to have run, which tests don't do.
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage'},
}

S3_BUCKET = os.environ.get('DJANGO_S3_BUCKET')
if S3_BUCKET:
    S3_REGION = os.environ.get('DJANGO_S3_REGION')
    if not S3_REGION:
        raise ImproperlyConfigured('Set DJANGO_S3_REGION (e.g. ap-northeast-1) along with DJANGO_S3_BUCKET.')
    S3_DOMAIN = os.environ.get('DJANGO_S3_CUSTOM_DOMAIN') or f'{S3_BUCKET}.s3.{S3_REGION}.amazonaws.com'
    S3_LOCATION = 'media'
    # Credentials come from AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY, which boto3 reads itself.
    STORAGES['default'] = {
        'BACKEND': 'storages.backends.s3.S3Storage',
        'OPTIONS': {
            'bucket_name': S3_BUCKET,
            'region_name': S3_REGION,
            'custom_domain': S3_DOMAIN,
            'location': S3_LOCATION,
            # Listings store the photo URLs, so they must be plain public URLs that never expire; the
            # bucket policy grants public read (new buckets have ACLs switched off).
            'querystring_auth': False,
            'default_acl': None,
            'file_overwrite': False,
            # Upload names are random and never reused, so browsers may cache photos for good.
            'object_parameters': {'CacheControl': 'public, max-age=31536000, immutable'},
        },
    }
    # Stored photo URLs start with this, which is how ListingPhotosMixin recognises its own uploads.
    MEDIA_URL = f'https://{S3_DOMAIN}/{S3_LOCATION}/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS Configuration
CORS_ALLOWED_ORIGINS = env_list(
    'DJANGO_CORS_ALLOWED_ORIGINS',
    'http://localhost:5173,http://127.0.0.1:5173,http://localhost:3000,http://127.0.0.1:3000',
)
CSRF_TRUSTED_ORIGINS = env_list('DJANGO_CSRF_TRUSTED_ORIGINS')

CORS_ALLOW_CREDENTIALS = True

# Rest Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        # Session auth that ignores the DevAuthBypassMiddleware user, so that user doesn't trigger CSRF.
        'common.middleware.DevAwareSessionAuthentication',
        # Dev-only fallback; DEBUG-gated internally, so it's inert in production. Kept last so
        # real JWT/Session credentials are always tried first.
        'common.middleware.DevAuthBypassAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    # Errors are {"detail": "message"} and/or {"field": ["message"]}: see common/exceptions.py.
    'EXCEPTION_HANDLER': 'common.exceptions.api_exception_handler',
    'NON_FIELD_ERRORS_KEY': 'detail',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    # How many proxies sit in front of Django and append to X-Forwarded-For. Rate limits key anonymous
    # callers by IP; with this unset DRF would key them by the whole header, which the caller writes
    # themselves, so a changing fake value would dodge every limit. Heroku's router is one proxy (it
    # appends the real client address); without the header (local dev) the socket address is used.
    'NUM_PROXIES': env_int('DJANGO_NUM_PROXIES', 1),
    # Rate limits for endpoints that invite abuse (views opt in with ScopedRateThrottle + throttle_scope).
    # Counted per signed-in user, or per IP address for anonymous requests.
    'DEFAULT_THROTTLE_RATES': {
        'auth': os.environ.get('DJANGO_THROTTLE_AUTH', '10/minute'),          # login, register
        'contact': os.environ.get('DJANGO_THROTTLE_CONTACT', '20/hour'),      # "contact seller"
        'report': os.environ.get('DJANGO_THROTTLE_REPORT', '20/hour'),        # report a listing
        'payments': os.environ.get('DJANGO_THROTTLE_PAYMENTS', '30/hour'),    # deposits, buy now, order payments
        'email': os.environ.get('DJANGO_THROTTLE_EMAIL', '5/hour'),           # password reset, new verification link
    },
}

# Throttle counts live in the cache. The default in-memory cache is per process, which is enough for
# a single server; with several workers, point CACHES at a shared cache (e.g. Redis) for exact limits.
# The test suite reuses user ids across tests, so counts would leak between them: tests get a cache
# that stores nothing (the throttle tests switch a real one back on).
if TESTING:
    CACHES = {'default': {'BACKEND': 'django.core.cache.backends.dummy.DummyCache'}}

if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Heroku's router terminates TLS and tells us the original scheme in X-Forwarded-Proto.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # Redirect plain HTTP to HTTPS; the test client speaks plain HTTP, so tests leave it off.
    SECURE_SSL_REDIRECT = env_bool('DJANGO_SECURE_SSL_REDIRECT', not TESTING)
    # Every .app domain is already HTTPS-only in browsers (the TLD is on the HSTS preload list), so a
    # year of HSTS on this host and its subdomains costs nothing. Set 0 on a host that isn't ready.
    SECURE_HSTS_SECONDS = env_int('DJANGO_SECURE_HSTS_SECONDS', 31536000)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Where the Django admin lives, e.g. a hard-to-guess `staff-x7k2/` in production so bots scanning for
# /admin/ never find the login page. Leading/trailing slashes are optional.
ADMIN_URL = os.environ.get('DJANGO_ADMIN_URL', 'admin').strip('/') + '/'
# Password sign-in on the admin (and the browsable API) is refused for this many minutes after this
# many failures in a row, per username and per client address (authentication/lockout.py).
LOGIN_LOCKOUT_FAILURES = env_int('LOGIN_LOCKOUT_FAILURES', 5)
LOGIN_LOCKOUT_MINUTES = env_int('LOGIN_LOCKOUT_MINUTES', 15)

# The OAuth client ID from Google Cloud Console (not a secret: the browser sees it too). Empty turns
# Google sign-in off. The frontend needs the same value as VITE_GOOGLE_CLIENT_ID.
GOOGLE_CLIENT_ID = os.environ.get('DJANGO_GOOGLE_CLIENT_ID', '').strip()

# SimpleJWT Configuration
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    # Each refresh hands out a new refresh token and retires the old one, and signing out retires the
    # current one (auth/logout/), so a copied token stops working instead of lasting its full lifetime.
    # Expired entries pile up in the blacklist tables: `manage.py flushexpiredtokens` clears them.
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}
