"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path
from datetime import timedelta
from decimal import Decimal

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_env_file(path):
    """Reads KEY=value lines from a local .env file; real environment variables take precedence."""
    if not path.exists():
        return
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        os.environ.setdefault(key.strip(), value.strip().strip('"\''))


def env_list(name, default=''):
    return [item.strip() for item in os.environ.get(name, default).split(',') if item.strip()]


def env_int(name, default):
    return int(os.environ.get(name, default))


def env_decimal(name, default):
    return Decimal(os.environ.get(name, default))


load_env_file(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# All deployment-specific values come from environment variables (or backend/.env locally; see
# .env.example). Defaults are production-safe: DEBUG is off unless explicitly enabled.
DEBUG = os.environ.get('DJANGO_DEBUG', '').lower() in ('1', 'true', 'yes')

SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured('Set DJANGO_SECRET_KEY (or DJANGO_DEBUG=1 for local development).')
    SECRET_KEY = 'django-insecure-local-development-only'

ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1' if DEBUG else '')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'django_filters',
    'post',
    'account',
    'authentication',
    'auction',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # Picks the response language from the frontend's Accept-Language header (see LANGUAGES below).
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'common.middleware.DevAuthBypassMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

AUTH_USER_MODEL = 'account.Account'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        # DJANGO_SQLITE_PATH lets the end-to-end tests run on a throwaway database.
        'NAME': Path(os.environ.get('DJANGO_SQLITE_PATH', BASE_DIR / 'db.sqlite3')),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Singapore'

USE_I18N = True

# API messages (validation errors, action results) are translated; the frontend sends the user's
# UI language as Accept-Language. Our own strings live in locale/; Django/DRF ship their own.
LANGUAGES = [
    ('en', 'English'),
    ('zh-hant', '繁體中文'),
]
LOCALE_PATHS = [BASE_DIR / 'locale']

USE_TZ = True

# Email
# Prints "sent" emails to the console in dev; swap for a real backend in production.
EMAIL_BACKEND = os.environ.get('DJANGO_EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
DEFAULT_FROM_EMAIL = os.environ.get('DJANGO_DEFAULT_FROM_EMAIL', 'no-reply@reptile-marketplace.local')
# Staff addresses that get alerts (e.g. a buyer reporting a problem with an order), comma-separated.
ADMINS = [('Staff', address) for address in env_list('DJANGO_ADMINS')]

# Auctions (see auction/)
AUCTION_CURRENCY = 'TWD'
# Deposit a bidder pays before bidding: this share of the starting price, but never below the minimum.
AUCTION_DEPOSIT_RATE = Decimal('0.10')
AUCTION_MIN_DEPOSIT = Decimal('100.00')
AUCTION_MIN_DURATION_HOURS = 1
AUCTION_MAX_DURATION_DAYS = 30
# Anti-sniping: a bid in the last AUCTION_EXTEND_WINDOW_MINUTES pushes the end time to at least
# AUCTION_EXTEND_BY_MINUTES from that bid, so others get a chance to answer it. 0 turns it off.
AUCTION_EXTEND_WINDOW_MINUTES = env_int('AUCTION_EXTEND_WINDOW_MINUTES', 5)
AUCTION_EXTEND_BY_MINUTES = env_int('AUCTION_EXTEND_BY_MINUTES', 5)
# Where deposits and buy-now payments go; see auction/payments.py. In DEBUG payments count as paid
# instantly so the flows can be tried locally; otherwise staff confirm them in the admin until a
# processor is wired up.
AUCTION_PAYMENT_GATEWAY = (
    'auction.payments.InstantPaymentGateway' if DEBUG else 'auction.payments.ManualPaymentGateway'
)

# After a sale (auction/models.py Order). Placeholder values: all of these are business decisions, so
# each can be changed with an environment variable without touching code.
# Hours the auction winner has to pay us the rest of the price; missing it forfeits their deposit.
ORDER_PAYMENT_HOURS = env_int('ORDER_PAYMENT_HOURS', 48)
# Hours a runner-up has to accept (pay for) an animal the seller offers them after the winner defaulted.
ORDER_RUNNER_UP_OFFER_HOURS = env_int('ORDER_RUNNER_UP_OFFER_HOURS', 48)
# Days the seller has, once we hold the full payment, to hand the animal over or ship it.
ORDER_HANDOVER_DAYS = env_int('ORDER_HANDOVER_DAYS', 5)
# Days the buyer then has to confirm it arrived intact (or report a problem) before the sale completes.
ORDER_CONFIRM_DAYS = env_int('ORDER_CONFIRM_DAYS', 3)
# Marketplace fee taken from the seller's payout, as a share of the price (0 = no fee yet).
ORDER_FEE_RATE = env_decimal('ORDER_FEE_RATE', '0')
# Bond a seller leaves with us before starting auctions, forfeited if they take a buyer's money and
# never hand over. 0 turns the requirement off.
SELLER_BOND_AMOUNT = env_decimal('SELLER_BOND_AMOUNT', '0')
# Accounts with at least this many incidents (unpaid buy-nows, defaults, no-shows) are highlighted
# in the admin's "Accounts to review". Nothing is blocked automatically.
INCIDENT_REVIEW_THRESHOLD = env_int('INCIDENT_REVIEW_THRESHOLD', 2)
# A listing reported by this many different accounts (with the reports still pending) is hidden until
# staff review it, and staff are emailed. 0 turns auto-hiding off: reports then only queue for review.
REPORT_AUTO_HIDE_THRESHOLD = env_int('REPORT_AUTO_HIDE_THRESHOLD', 0)
# Saved searches a user may keep (each is emailed about by `manage.py send_search_alerts`).
SAVED_SEARCH_LIMIT = env_int('SAVED_SEARCH_LIMIT', 20)
# Where the website lives, for links in emails (e.g. https://example.com). No trailing slash.
FRONTEND_URL = os.environ.get('DJANGO_FRONTEND_URL', 'http://localhost:5173').rstrip('/')
# People who saved a listing get at most one price-drop email per listing in this many hours, so a
# seller can't mass-email them by lowering the price a little at a time.
PRICE_DROP_EMAIL_HOURS = env_int('PRICE_DROP_EMAIL_HOURS', 24)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# User-uploaded listing photos. Served by Django only when DEBUG is on; in production point your web
# server (or object storage) at MEDIA_ROOT.
MEDIA_URL = '/media/'
MEDIA_ROOT = Path(os.environ.get('DJANGO_MEDIA_ROOT', BASE_DIR / 'media'))

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS Configuration
CORS_ALLOWED_ORIGINS = env_list(
    'DJANGO_CORS_ALLOWED_ORIGINS',
    'http://localhost:5173,http://127.0.0.1:5173,http://localhost:3000,http://127.0.0.1:3000',
)
CSRF_TRUSTED_ORIGINS = env_list('DJANGO_CSRF_TRUSTED_ORIGINS')

CORS_ALLOW_CREDENTIALS = True

# Rest Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        # Session auth that ignores the DevAuthBypassMiddleware user, so that user doesn't trigger CSRF.
        'common.middleware.DevAwareSessionAuthentication',
        # Dev-only fallback; DEBUG-gated internally, so it's inert in production. Kept last so
        # real JWT/Session credentials are always tried first.
        'common.middleware.DevAuthBypassAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    # Rate limits for endpoints that invite abuse (views opt in with ScopedRateThrottle + throttle_scope).
    # Counted per signed-in user, or per IP address for anonymous requests.
    'DEFAULT_THROTTLE_RATES': {
        'auth': os.environ.get('DJANGO_THROTTLE_AUTH', '10/minute'),          # login, register
        'contact': os.environ.get('DJANGO_THROTTLE_CONTACT', '20/hour'),      # "contact seller"
        'report': os.environ.get('DJANGO_THROTTLE_REPORT', '20/hour'),        # report a listing
        'payments': os.environ.get('DJANGO_THROTTLE_PAYMENTS', '30/hour'),    # deposits, buy now, order payments
    },
}

# Throttle counts live in the cache. The default in-memory cache is per process, which is enough for
# a single server; with several workers, point CACHES at a shared cache (e.g. Redis) for exact limits.
# The test suite reuses user ids across tests, so counts would leak between them: tests get a cache
# that stores nothing (the throttle tests switch a real one back on).
if sys.argv[1:2] == ['test']:
    CACHES = {'default': {'BACKEND': 'django.core.cache.backends.dummy.DummyCache'}}

if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# SimpleJWT Configuration
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'AUTH_HEADER_TYPES': ('Bearer',),
}
