# Generated by Django 5.2.8 on 2026-02-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('phone_num', models.CharField(blank=True, max_length=15, null=True)),
                ('personal_id', models.CharField(max_length=12, unique=True)),
                ('line_id', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
