# Generated by Django 5.2.8 on 2026-09-01 06:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('hobbyist', 'Hobbyist'), ('commercial', 'Commercial')], default='hobbyist', max_length=20),
        ),
        migrations.AddField(
            model_name='account',
            name='is_paid_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='seller_rating',
            field=models.FloatField(blank=True, default=0.0, help_text='Average seller rating (0-5)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
