# Generated by Django 5.2.8 on 2026-09-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_account_type_account_is_paid_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='account',
            name='facebook',
            field=models.CharField(blank=True, help_text='Facebook page name or URL', max_length=200),
        ),
        migrations.AddField(
            model_name='account',
            name='instagram',
            field=models.CharField(blank=True, help_text='Instagram handle, e.g. @geckogarden', max_length=60),
        ),
    ]
