# Generated by Django 5.2.8 on 2026-09-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="email_verified",
            field=models.BooleanField(default=True),
        ),
    ]
