# Generated by Django 5.2.8 on 2026-09-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_account_email_unique_ci"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="google_id",
            field=models.CharField(
                blank=True, editable=False, max_length=255, null=True, unique=True
            ),
        ),
    ]
